/* eslint-disable */
import './angle-down'
import './circle'
import './code'
import './database'
import './edit'
import './font'
import './layer-group'
import './link'
import './list'
import './object-group'
import './paragraph'
import './podcast'
import './square'
import './table'
import './th-list'
import './trash-alt'
import './window-maximize'
